# Generated by Django 3.0.4 on 2020-06-04 05:22

from django.db import migrations, models
import invoice.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[invoice.validators.validate_file_extension])),
                ('digitizaton_status', models.CharField(default='digitization_pending', max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
