# Generated by Django 3.0.4 on 2020-06-05 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Seller',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='buyer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='invoice_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='invoice_number',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='order_number',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InvoiveItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('item_tax', models.FloatField(blank=True, null=True)),
                ('item_total', models.FloatField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.File')),
            ],
        ),
    ]
