# Generated by Django 3.0.4 on 2020-06-05 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20200605_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiveitem',
            old_name='file',
            new_name='File',
        ),
    ]
