# Generated by Django 3.0.4 on 2020-06-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20200605_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='Seller',
            new_name='bill_to',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='buyer',
            new_name='ship_to',
        ),
        migrations.RemoveField(
            model_name='file',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='file',
            name='tax',
        ),
        migrations.AddField(
            model_name='file',
            name='invoice_from',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='to',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='invoiveitem',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoiveitem',
            name='item',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='invoice_date',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='total_amount',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='invoiveitem',
            name='item_tax',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='invoiveitem',
            name='item_total',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='invoiveitem',
            name='price',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='invoiveitem',
            name='quantity',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
