# Generated by Django 3.0.4 on 2020-06-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20200605_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, null=True)),
                ('quantity', models.CharField(max_length=25, null=True)),
                ('price', models.CharField(max_length=25, null=True)),
                ('item_tax', models.CharField(blank=True, max_length=25, null=True)),
                ('item_total', models.CharField(blank=True, max_length=25, null=True)),
                ('File', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.File')),
            ],
        ),
        migrations.DeleteModel(
            name='InvoiveItem',
        ),
    ]
